### ISSUE TITLE
My spotify-cli couldn't work because dial tcp 172.217.160.81:443: connect: connection refused

### ISSUE THREAD

**Issue by hulu101** [khanhas/homebrew-tap#1]
Can anyone help me? Pls

**Comment by hulu101** [comment]
go: github.com/go-ini/ini@v1.55.0: Get "https://proxy.golang.org/github.com/go-ini/ini/@v/v1.55.0.mod": dial tcp 172.217.160.81:443: connect: connection refused

**Comment by hulu101** [comment]
hulu101@LAPTOP-NILPNCDC:/mnt/c/WINDOWS/system32$ brew install khanhas/tap/spicetify-cli
sleep: cannot read realtime clock: Invalid argument
Updating Homebrew...
==> Installing spicetify-cli from khanhas/tap
==> Downloading https://github.com/khanhas/spicetify-cli/archive/v1.0.2.tar.gz
Already downloaded: /home/hulu101/.cache/Homebrew/downloads/b5fb286ce31af42b79eb089f56b414c06dd7f8977f7ed97a84803cdc1e1c0df5--spicetify-cli-1.0.2.tar.gz
==> go build spicetify
Last 15 lines from /home/hulu101/.cache/Homebrew/Logs/spicetify-cli/01.go:
2020-08-01 12:19:43 +0800

go
build
-o
spicetify

go: github.com/go-ini/ini@v1.55.0: Get "https://proxy.golang.org/github.com/go-ini/ini/@v/v1.55.0.mod": dial tcp 172.217.160.81:443: connect: connection refused

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/khanhas/homebrew-tap/issues

**Comment by khanhas** [comment]
Please use prebuilt package instead:
https://github.com/khanhas/spicetify-cli/wiki/Installation#with-shell-pre-built-binary

**Comment by hulu101** [comment]
*I have finished downloading and installing,but it still not work,like*:
PS C:\Users\pc> spicetify backup apply enable-devtool
spicetify v1.0.2
info There is available backup.
info Clear current backup:
warning After clearing backup, Spotify cannot be backed up again.
info Please restore first then backup, run "spicetify restore backup" or
re-install Spotify then run "spicetify backup".
PS C:\Users\pc>
PS C:\Users\pc> spicetify update
spicetify v1.0.2
error Theme "Vaporwave" not found


khanhas <notifications@github.com> 于2020年8月1日周六 下午12:54写道：

**Comment by khanhas** [comment]
Reinstall Spotify and run `spicetify backup apply`

**Comment by hulu101** [comment]
*But it is same：*
error Theme "Vaporwave" not found
PS C:\Users\pc>
PS C:\Users\pc> spicetify update
spicetify v1.0.2
error Theme "Vaporwave" not found


khanhas <notifications@github.com> 于2020年8月1日周六 下午3:47写道：

**Comment by khanhas** [comment]
Because you don't have that theme!
Follow these instruction:
https://github.com/morpheusthewhite/spicetify-themes

**Comment by hulu101** [comment]
But I do have the themes  in
*C:\Users\pc\.spicetify\Themes\spicetify-themes-master*
Is this right?*So sorry for disturbing such a long time.*

khanhas <notifications@github.com> 于2020年8月1日周六 下午6:37写道：

**Comment by khanhas** [comment]
Please read the spicetify-themes readme page and follow the instruction.
